@startuml
"Data Gate Client 1" --> "Data Gate Server 1": Establish Connection
"Data Gate Client 1" --> "Data Gate Server 1" : Send Subscription info(collections,replication strategy, last time stamp)
"Data Gate Server 1" --> "Kafka Cluster" : Subscribe to Update Events for Collections
"Data Gate Server 1" --> "MongoDB Cluster" : Get Updates since timestamp
"MongoDB Cluster" --> "Data Gate Server 1" : Return Result
"Data Gate Server 1" --> "Data Gate Client 1" : Send Updates
"Data Gate Client 2" --> "Data Gate Server 2" : Send Updates
"Data Gate Server 2" --> "Kafka Cluster" : Send Update Event for Collection
"Data Gate Server 2" --> "MongoDB Cluster" : Write Changes
"Kafka Cluster" --> "Data Gate Server 1" : Send Update Event for Collection
"Data Gate Server 1" --> "Data Gate Client 1" : Send Updates

@enduml
